/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPriceCalculatorRouteImport } from './routes/_app.price-calculator'
import { Route as AppOtaAccountsRouteImport } from './routes/_app.ota-accounts'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppShopsIndexRouteImport } from './routes/_app.shops.index'
import { Route as AppDataPoolIndexRouteImport } from './routes/_app.data-pool.index'
import { Route as AppShopsNewRouteImport } from './routes/_app.shops.new'
import { Route as AppShopsHotelsRouteImport } from './routes/_app.shops.hotels'
import { Route as AppShopsShopIdRouteImport } from './routes/_app.shops.$shopId'
import { Route as AppDataPoolHotelIdRouteImport } from './routes/_app.data-pool.$hotelId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPriceCalculatorRoute = AppPriceCalculatorRouteImport.update({
  id: '/price-calculator',
  path: '/price-calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppOtaAccountsRoute = AppOtaAccountsRouteImport.update({
  id: '/ota-accounts',
  path: '/ota-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsIndexRoute = AppShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataPoolIndexRoute = AppDataPoolIndexRouteImport.update({
  id: '/data-pool/',
  path: '/data-pool/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsNewRoute = AppShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsHotelsRoute = AppShopsHotelsRouteImport.update({
  id: '/shops/hotels',
  path: '/shops/hotels',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsShopIdRoute = AppShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => AppRoute,
} as any)
const AppDataPoolHotelIdRoute = AppDataPoolHotelIdRouteImport.update({
  id: '/data-pool/$hotelId',
  path: '/data-pool/$hotelId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/ota-accounts': typeof AppOtaAccountsRoute
  '/price-calculator': typeof AppPriceCalculatorRoute
  '/data-pool/$hotelId': typeof AppDataPoolHotelIdRoute
  '/shops/$shopId': typeof AppShopsShopIdRoute
  '/shops/hotels': typeof AppShopsHotelsRoute
  '/shops/new': typeof AppShopsNewRoute
  '/data-pool/': typeof AppDataPoolIndexRoute
  '/shops/': typeof AppShopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/ota-accounts': typeof AppOtaAccountsRoute
  '/price-calculator': typeof AppPriceCalculatorRoute
  '/data-pool/$hotelId': typeof AppDataPoolHotelIdRoute
  '/shops/$shopId': typeof AppShopsShopIdRoute
  '/shops/hotels': typeof AppShopsHotelsRoute
  '/shops/new': typeof AppShopsNewRoute
  '/data-pool': typeof AppDataPoolIndexRoute
  '/shops': typeof AppShopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/ota-accounts': typeof AppOtaAccountsRoute
  '/_app/price-calculator': typeof AppPriceCalculatorRoute
  '/_app/data-pool/$hotelId': typeof AppDataPoolHotelIdRoute
  '/_app/shops/$shopId': typeof AppShopsShopIdRoute
  '/_app/shops/hotels': typeof AppShopsHotelsRoute
  '/_app/shops/new': typeof AppShopsNewRoute
  '/_app/data-pool/': typeof AppDataPoolIndexRoute
  '/_app/shops/': typeof AppShopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/orders'
    | '/ota-accounts'
    | '/price-calculator'
    | '/data-pool/$hotelId'
    | '/shops/$shopId'
    | '/shops/hotels'
    | '/shops/new'
    | '/data-pool/'
    | '/shops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/orders'
    | '/ota-accounts'
    | '/price-calculator'
    | '/data-pool/$hotelId'
    | '/shops/$shopId'
    | '/shops/hotels'
    | '/shops/new'
    | '/data-pool'
    | '/shops'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/dashboard'
    | '/_app/orders'
    | '/_app/ota-accounts'
    | '/_app/price-calculator'
    | '/_app/data-pool/$hotelId'
    | '/_app/shops/$shopId'
    | '/_app/shops/hotels'
    | '/_app/shops/new'
    | '/_app/data-pool/'
    | '/_app/shops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/price-calculator': {
      id: '/_app/price-calculator'
      path: '/price-calculator'
      fullPath: '/price-calculator'
      preLoaderRoute: typeof AppPriceCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ota-accounts': {
      id: '/_app/ota-accounts'
      path: '/ota-accounts'
      fullPath: '/ota-accounts'
      preLoaderRoute: typeof AppOtaAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shops/': {
      id: '/_app/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof AppShopsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-pool/': {
      id: '/_app/data-pool/'
      path: '/data-pool'
      fullPath: '/data-pool/'
      preLoaderRoute: typeof AppDataPoolIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shops/new': {
      id: '/_app/shops/new'
      path: '/shops/new'
      fullPath: '/shops/new'
      preLoaderRoute: typeof AppShopsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shops/hotels': {
      id: '/_app/shops/hotels'
      path: '/shops/hotels'
      fullPath: '/shops/hotels'
      preLoaderRoute: typeof AppShopsHotelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shops/$shopId': {
      id: '/_app/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AppShopsShopIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-pool/$hotelId': {
      id: '/_app/data-pool/$hotelId'
      path: '/data-pool/$hotelId'
      fullPath: '/data-pool/$hotelId'
      preLoaderRoute: typeof AppDataPoolHotelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOtaAccountsRoute: typeof AppOtaAccountsRoute
  AppPriceCalculatorRoute: typeof AppPriceCalculatorRoute
  AppDataPoolHotelIdRoute: typeof AppDataPoolHotelIdRoute
  AppShopsShopIdRoute: typeof AppShopsShopIdRoute
  AppShopsHotelsRoute: typeof AppShopsHotelsRoute
  AppShopsNewRoute: typeof AppShopsNewRoute
  AppDataPoolIndexRoute: typeof AppDataPoolIndexRoute
  AppShopsIndexRoute: typeof AppShopsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOtaAccountsRoute: AppOtaAccountsRoute,
  AppPriceCalculatorRoute: AppPriceCalculatorRoute,
  AppDataPoolHotelIdRoute: AppDataPoolHotelIdRoute,
  AppShopsShopIdRoute: AppShopsShopIdRoute,
  AppShopsHotelsRoute: AppShopsHotelsRoute,
  AppShopsNewRoute: AppShopsNewRoute,
  AppDataPoolIndexRoute: AppDataPoolIndexRoute,
  AppShopsIndexRoute: AppShopsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
