/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShopsRouteImport } from './routes/_app.shops'
import { Route as AppPriceCalculatorRouteImport } from './routes/_app.price-calculator'
import { Route as AppOtaAccountsRouteImport } from './routes/_app.ota-accounts'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDataPoolIndexRouteImport } from './routes/_app.data-pool.index'
import { Route as AppDataPoolHotelIdRouteImport } from './routes/_app.data-pool.$hotelId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShopsRoute = AppShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceCalculatorRoute = AppPriceCalculatorRouteImport.update({
  id: '/price-calculator',
  path: '/price-calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppOtaAccountsRoute = AppOtaAccountsRouteImport.update({
  id: '/ota-accounts',
  path: '/ota-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDataPoolIndexRoute = AppDataPoolIndexRouteImport.update({
  id: '/data-pool/',
  path: '/data-pool/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataPoolHotelIdRoute = AppDataPoolHotelIdRouteImport.update({
  id: '/data-pool/$hotelId',
  path: '/data-pool/$hotelId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/ota-accounts': typeof AppOtaAccountsRoute
  '/price-calculator': typeof AppPriceCalculatorRoute
  '/shops': typeof AppShopsRoute
  '/data-pool/$hotelId': typeof AppDataPoolHotelIdRoute
  '/data-pool/': typeof AppDataPoolIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/orders': typeof AppOrdersRoute
  '/ota-accounts': typeof AppOtaAccountsRoute
  '/price-calculator': typeof AppPriceCalculatorRoute
  '/shops': typeof AppShopsRoute
  '/data-pool/$hotelId': typeof AppDataPoolHotelIdRoute
  '/data-pool': typeof AppDataPoolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/ota-accounts': typeof AppOtaAccountsRoute
  '/_app/price-calculator': typeof AppPriceCalculatorRoute
  '/_app/shops': typeof AppShopsRoute
  '/_app/data-pool/$hotelId': typeof AppDataPoolHotelIdRoute
  '/_app/data-pool/': typeof AppDataPoolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/orders'
    | '/ota-accounts'
    | '/price-calculator'
    | '/shops'
    | '/data-pool/$hotelId'
    | '/data-pool/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/orders'
    | '/ota-accounts'
    | '/price-calculator'
    | '/shops'
    | '/data-pool/$hotelId'
    | '/data-pool'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/orders'
    | '/_app/ota-accounts'
    | '/_app/price-calculator'
    | '/_app/shops'
    | '/_app/data-pool/$hotelId'
    | '/_app/data-pool/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/shops': {
      id: '/_app/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof AppShopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-calculator': {
      id: '/_app/price-calculator'
      path: '/price-calculator'
      fullPath: '/price-calculator'
      preLoaderRoute: typeof AppPriceCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ota-accounts': {
      id: '/_app/ota-accounts'
      path: '/ota-accounts'
      fullPath: '/ota-accounts'
      preLoaderRoute: typeof AppOtaAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-pool/': {
      id: '/_app/data-pool/'
      path: '/data-pool'
      fullPath: '/data-pool/'
      preLoaderRoute: typeof AppDataPoolIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-pool/$hotelId': {
      id: '/_app/data-pool/$hotelId'
      path: '/data-pool/$hotelId'
      fullPath: '/data-pool/$hotelId'
      preLoaderRoute: typeof AppDataPoolHotelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOtaAccountsRoute: typeof AppOtaAccountsRoute
  AppPriceCalculatorRoute: typeof AppPriceCalculatorRoute
  AppShopsRoute: typeof AppShopsRoute
  AppDataPoolHotelIdRoute: typeof AppDataPoolHotelIdRoute
  AppDataPoolIndexRoute: typeof AppDataPoolIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOtaAccountsRoute: AppOtaAccountsRoute,
  AppPriceCalculatorRoute: AppPriceCalculatorRoute,
  AppShopsRoute: AppShopsRoute,
  AppDataPoolHotelIdRoute: AppDataPoolHotelIdRoute,
  AppDataPoolIndexRoute: AppDataPoolIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
